import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'th' | 'en' | 'jp';

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string, args?: { [key: string]: string }) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>((localStorage.getItem('language') as Language) || 'th');

  React.useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const t = (key: string, args: { [key: string]: string } = {}) => {
    let translation = translations[language][key] || translations['th'][key] || key;

    for (const arg in args) {
      translation = translation.replace(`{${arg}}`, args[arg]);
    }

    return translation;
  };

  const translations = {
  th: {
    'login': 'เข้าสู่ระบบ',
    'logout': 'ออกจากระบบ',
    'register': 'สมัครสมาชิก',
    'profile': 'โปรไฟล์',
    'favorites': 'รายการโปรด',
    'home': 'หน้าหลัก',
    'search.placeholder': 'ค้นหา...',
    'search.button': 'ค้นหา',
    'account.detail': 'รายละเอียดบัญชี',
    'auth.login.required': 'ต้องเข้าสู่ระบบ',
    'auth.login.required.description': 'กรุณาเข้าสู่ระบบเพื่อดำเนินการต่อ',
    'auth.cancel': 'ยกเลิก',
    'category.select': 'เลือกหมวดหมู่',
    'category.all': 'ทั้งหมด',
    'category.restaurant': 'ร้านอาหาร',
    'category.hotel': 'โรงแรม',
    'category.travel': 'ท่องเที่ยว',
    'category.shopping': 'ช้อปปิ้ง',
    'category.beauty': 'ความงาม',
    'category.health': 'สุขภาพ',
    'category.education': 'การศึกษา',
    'category.finance': 'การเงิน',
    'category.other': 'อื่นๆ',
    'category.restaurant.icon': '🍔',
    'category.hotel.icon': '🏨',
    'category.travel.icon': '✈️',
    'category.shopping.icon': '🛍️',
    'category.beauty.icon': '💄',
    'category.health.icon': '⚕️',
    'category.education.icon': '📚',
    'category.finance.icon': '💰',
    'category.other.icon': '✨',
    '404.title': 'ไม่พบหน้า',
    '404.back': 'กลับสู่หน้าหลัก',
    'favorites.title': 'รายการโปรดของฉัน',
    'favorites.description': 'บัญชี LINE OA ที่คุณชื่นชอบ',
    'favorites.accounts': 'บัญชี',
    'favorites.empty.title': 'ไม่มีรายการโปรด',
    'favorites.empty.description': 'เพิ่มบัญชี LINE OA ที่คุณชื่นชอบเพื่อดูที่นี่',
    'favorites.browse': 'เลือกดูบัญชี LINE OA',
    'share.title': 'แชร์',
    'share.url': 'URL',
    'share.copied.title': 'คัดลอก URL แล้ว',
    'share.copied.description': 'URL ถูกคัดลอกไปยังคลิปบอร์ดแล้ว',
    'share.error.title': 'เกิดข้อผิดพลาด',
    'share.error.description': 'ไม่สามารถคัดลอก URL ได้',
    'share.button': 'แชร์',
    'rating.title': 'ให้คะแนน',
    'rating.your.rating': 'คะแนนของคุณ',
    'rating.login.required': 'ต้องเข้าสู่ระบบ',
    'rating.login.required.description': 'กรุณาเข้าสู่ระบบเพื่อให้คะแนน',
    'rating.login.required.message': 'เข้าสู่ระบบเพื่อทำการให้คะแนน',
    'rating.success.title': 'ขอบคุณสำหรับการให้คะแนน',
    'rating.success.description': 'คะแนนของคุณได้รับการบันทึกแล้ว',
    'rating.submitted': 'คุณได้ให้คะแนนแล้ว',
    'review.title': 'เขียนรีวิว',
    'review.rating': 'คะแนน',
    'review.comment': 'ความคิดเห็น',
    'review.comment.placeholder': 'เขียนความคิดเห็นของคุณที่นี่...',
    'review.submit': 'ส่งรีวิว',
    'review.submit.success': 'ส่งรีวิวสำเร็จ',
    'review.submit.success.description': 'ขอบคุณสำหรับรีวิวของคุณ',
    'review.error.login.required': 'ต้องเข้าสู่ระบบ',
    'review.error.login.required.description': 'กรุณาเข้าสู่ระบบเพื่อเขียนรีวิว',
    'review.error.rating.required': 'กรุณาให้คะแนน',
    'review.error.rating.required.description': 'กรุณาเลือกคะแนนก่อนส่งรีวิว',
    'manager.accounts': 'บัญชีของคุณ',
    'manager.limit.info': 'คุณสามารถสร้างบัญชี LINE OA ได้อีก',
    'manager.limit.reached': 'คุณได้สร้างบัญชี LINE OA ครบตามจำนวนที่กำหนดแล้ว',
    
    // Chat translations
    'chat.title.organizer': 'ติดต่อผู้ดูแลระบบ (ผู้จัดการ)',
    'chat.title.general': 'ติดต่อผู้ดูแลระบบ',
    'chat.description.organizer': 'ส่งข้อความถึงผู้ดูแลระบบเกี่ยวกับการจัดการบัญชี LINE OA',
    'chat.description.general': 'ส่งข้อความถึงผู้ดูแลระบบเพื่อขอความช่วยเหลือ',
    'chat.placeholder': 'พิมพ์ข้อความของคุณที่นี่...',
    'chat.send': 'ส่งข้อความ',
    'chat.empty': 'ยังไม่มีข้อความ',
    'chat.response.time': 'ผู้ดูแลระบบจะตอบกลับภายใน 24 ชั่วโมง',

    // Account edit translations
    'account.edit.title': 'แก้ไขข้อมูลบัญชี LINE OA',
    'account.edit.button': 'แก้ไข',
    'account.edit.save': 'บันทึกการเปลี่ยนแปลง',
    'account.edit.delete': 'ลบบัญชี',
    'account.edit.success': 'บันทึกข้อมูลสำเร็จ',
    'account.edit.success.description': 'ข้อมูลบัญชีถูกอัปเดตเรียบร้อยแล้ว',
    'account.edit.error.required': 'กรุณากรอกข้อมูลที่จำเป็น',
    'account.edit.error.required.description': 'ชื่อ, คำอธิบาย และ LINE ID เป็นข้อมูลที่จำเป็น',

    // Account form translations
    'account.form.name': 'ชื่อบัญชี',
    'account.form.name.placeholder': 'กรอกชื่อบัญชี LINE OA',
    'account.form.description': 'คำอธิบาย',
    'account.form.description.placeholder': 'อธิบายเกี่ยวกับบัญชี LINE OA ของคุณ',
    'account.form.category': 'หมวดหมู่',
    'account.form.category.placeholder': 'เลือกหมวดหมู่',
    'account.form.lineId': 'LINE ID',
    'account.form.lineId.placeholder': 'กรอก LINE ID',
    'account.form.tags': 'แท็ก',
    'account.form.tags.placeholder': 'กรอกแท็ก เช่น ร้านอาหาร, เดลิเวอรี่',
    'account.form.tags.help': 'แยกแท็กด้วยเครื่องหมายจุลภาค',
    'account.form.location': 'ที่อยู่',
    'account.form.location.placeholder': 'กรอกที่อยู่ (ไม่บังคับ)',

    // Account delete translations
    'account.delete.button': 'ลบบัญชี',
    'account.delete.success': 'ลบบัญชีสำเร็จ',
    'account.delete.success.description': 'บัญชีถูกลบออกจากระบบเรียบร้อยแล้ว',
    'account.delete.error.promoted': 'ไม่สามารถลบได้',
    'account.delete.error.promoted.description': 'ต้องยกเลิกการโปรโมตก่อนจึงจะลบบัญชีได้',
    'account.delete.warning.promoted': 'บัญชีนี้กำลังทำการโปรโมตอยู่ ต้องยกเลิกการโปรโมตก่อนจึงจะสามารถลบได้',
    'account.delete.confirm.title': 'ยืนยันการลบบัญชี',
    'account.delete.confirm.description': 'คุณแน่ใจหรือไม่ที่จะลบบัญชี "{name}" การดำเนินการนี้ไม่สามารถยกเลิกได้',
    'account.delete.confirm.button': 'ลบบัญชี',

    // Promotion translations
    'account.promoted': 'กำลังโปรโมต',
    'promotion.cancel.button': 'ยกเลิกโปรโมต',
    'promotion.cancel.success': 'ยกเลิกการโปรโมตสำเร็จ',
    'promotion.cancel.success.description': 'การโปรโมตถูกยกเลิกเรียบร้อยแล้ว',
    'promotion.cancel.confirm.title': 'ยืนยันการยกเลิกโปรโมต',
    'promotion.cancel.confirm.description': 'คุณแน่ใจหรือไม่ที่จะยกเลิกการโปรโมตสำหรับ "{name}"',
    'promotion.cancel.confirm.button': 'ยกเลิกโปรโมต',
  },
  en: {
    'login': 'Login',
    'logout': 'Logout',
    'register': 'Register',
    'profile': 'Profile',
    'favorites': 'Favorites',
    'home': 'Home',
    'search.placeholder': 'Search...',
    'search.button': 'Search',
    'account.detail': 'Account Detail',
    'auth.login.required': 'Login Required',
    'auth.login.required.description': 'Please login to continue',
    'auth.cancel': 'Cancel',
    'category.select': 'Select Category',
    'category.all': 'All',
    'category.restaurant': 'Restaurant',
    'category.hotel': 'Hotel',
    'category.travel': 'Travel',
    'category.shopping': 'Shopping',
    'category.beauty': 'Beauty',
    'category.health': 'Health',
    'category.education': 'Education',
    'category.finance': 'Finance',
    'category.other': 'Other',
    'category.restaurant.icon': '🍔',
    'category.hotel.icon': '🏨',
    'category.travel.icon': '✈️',
    'category.shopping.icon': '🛍️',
    'category.beauty.icon': '💄',
    'category.health.icon': '⚕️',
    'category.education.icon': '📚',
    'category.finance.icon': '💰',
    'category.other.icon': '✨',
    '404.title': 'Page Not Found',
    '404.back': 'Back to Home',
    'favorites.title': 'My Favorites',
    'favorites.description': 'Your favorite LINE OA accounts',
    'favorites.accounts': 'accounts',
    'favorites.empty.title': 'No Favorites',
    'favorites.empty.description': 'Add your favorite LINE OA accounts to view here',
    'favorites.browse': 'Browse LINE OA Accounts',
    'share.title': 'Share',
    'share.url': 'URL',
    'share.copied.title': 'URL Copied',
    'share.copied.description': 'URL has been copied to clipboard',
    'share.error.title': 'Error',
    'share.error.description': 'Failed to copy URL',
    'share.button': 'Share',
    'rating.title': 'Rating',
    'rating.your.rating': 'Your Rating',
    'rating.login.required': 'Login Required',
    'rating.login.required.description': 'Please login to rate',
    'rating.login.required.message': 'Login to submit rating',
    'rating.success.title': 'Thanks for Rating',
    'rating.success.description': 'Your rating has been submitted',
    'rating.submitted': 'You have rated',
    'review.title': 'Write a Review',
    'review.rating': 'Rating',
    'review.comment': 'Comment',
    'review.comment.placeholder': 'Write your comment here...',
    'review.submit': 'Submit Review',
    'review.submit.success': 'Review Submitted',
    'review.submit.success.description': 'Thank you for your review',
    'review.error.login.required': 'Login Required',
    'review.error.login.required.description': 'Please login to write a review',
    'review.error.rating.required': 'Rating Required',
    'review.error.rating.required.description': 'Please select a rating before submitting',
    'manager.accounts': 'Your Accounts',
    'manager.limit.info': 'You can create more LINE OA accounts',
    'manager.limit.reached': 'You have reached the limit of LINE OA accounts',
    
    // Chat translations
    'chat.title.organizer': 'Contact Admin (Manager)',
    'chat.title.general': 'Contact Admin',
    'chat.description.organizer': 'Send message to admin about LINE OA account management',
    'chat.description.general': 'Send message to admin for assistance',
    'chat.placeholder': 'Type your message here...',
    'chat.send': 'Send Message',
    'chat.empty': 'No messages yet',
    'chat.response.time': 'Admin will respond within 24 hours',

    // Account edit translations
    'account.edit.title': 'Edit LINE OA Account',
    'account.edit.button': 'Edit',
    'account.edit.save': 'Save Changes',
    'account.edit.delete': 'Delete Account',
    'account.edit.success': 'Successfully saved',
    'account.edit.success.description': 'Account information has been updated',
    'account.edit.error.required': 'Please fill required fields',
    'account.edit.error.required.description': 'Name, description and LINE ID are required',

    // Account form translations
    'account.form.name': 'Account Name',
    'account.form.name.placeholder': 'Enter LINE OA account name',
    'account.form.description': 'Description',
    'account.form.description.placeholder': 'Describe your LINE OA account',
    'account.form.category': 'Category',
    'account.form.category.placeholder': 'Select category',
    'account.form.lineId': 'LINE ID',
    'account.form.lineId.placeholder': 'Enter LINE ID',
    'account.form.tags': 'Tags',
    'account.form.tags.placeholder': 'Enter tags, e.g. restaurant, delivery',
    'account.form.tags.help': 'Separate tags with commas',
    'account.form.location': 'Address',
    'account.form.location.placeholder': 'Enter address (optional)',

    // Account delete translations
    'account.delete.button': 'Delete Account',
    'account.delete.success': 'Successfully deleted',
    'account.delete.success.description': 'Account has been removed from the system',
    'account.delete.error.promoted': 'Cannot delete',
    'account.delete.error.promoted.description': 'Must cancel promotion before deleting account',
    'account.delete.warning.promoted': 'This account is currently being promoted. Cancel promotion before deleting.',
    'account.delete.confirm.title': 'Confirm Account Deletion',
    'account.delete.confirm.description': 'Are you sure you want to delete account "{name}"? This action cannot be undone.',
    'account.delete.confirm.button': 'Delete Account',

    // Promotion translations
    'account.promoted': 'Promoted',
    'promotion.cancel.button': 'Cancel Promotion',
    'promotion.cancel.success': 'Promotion cancelled',
    'promotion.cancel.success.description': 'Promotion has been cancelled successfully',
    'promotion.cancel.confirm.title': 'Confirm Promotion Cancellation',
    'promotion.cancel.confirm.description': 'Are you sure you want to cancel promotion for "{name}"?',
    'promotion.cancel.confirm.button': 'Cancel Promotion',
  },
  jp: {
    'login': 'ログイン',
    'logout': 'ログアウト',
    'register': '登録',
    'profile': 'プロフィール',
    'favorites': 'お気に入り',
    'home': 'ホーム',
    'search.placeholder': '検索...',
    'search.button': '検索',
    'account.detail': 'アカウント詳細',
    'auth.login.required': 'ログインが必要です',
    'auth.login.required.description': '続行するにはログインしてください',
    'auth.cancel': 'キャンセル',
    'category.select': 'カテゴリを選択',
    'category.all': 'すべて',
    'category.restaurant': 'レストラン',
    'category.hotel': 'ホテル',
    'category.travel': '旅行',
    'category.shopping': 'ショッピング',
    'category.beauty': '美容',
    'category.health': '健康',
    'category.education': '教育',
    'category.finance': '金融',
    'category.other': 'その他',
    'category.restaurant.icon': '🍔',
    'category.hotel.icon': '🏨',
    'category.travel.icon': '✈️',
    'category.shopping.icon': '🛍️',
    'category.beauty.icon': '💄',
    'category.health.icon': '⚕️',
    'category.education.icon': '📚',
    'category.finance.icon': '💰',
    'category.other.icon': '✨',
    '404.title': 'ページが見つかりません',
    '404.back': 'ホームに戻る',
    'favorites.title': 'お気に入り',
    'favorites.description': 'お気に入りのLINE OAアカウント',
    'favorites.accounts': 'アカウント',
    'favorites.empty.title': 'お気に入りはありません',
    'favorites.empty.description': 'お気に入りのLINE OAアカウントを追加してここに表示',
    'favorites.browse': 'LINE OAアカウントを閲覧',
    'share.title': 'シェア',
    'share.url': 'URL',
    'share.copied.title': 'URLをコピーしました',
    'share.copied.description': 'URLがクリップボードにコピーされました',
    'share.error.title': 'エラー',
    'share.error.description': 'URLのコピーに失敗しました',
    'share.button': 'シェア',
    'rating.title': '評価',
    'rating.your.rating': 'あなたの評価',
    'rating.login.required': 'ログインが必要です',
    'rating.login.required.description': '評価するにはログインしてください',
    'rating.login.required.message': '評価を送信するにはログインしてください',
    'rating.success.title': '評価ありがとうございます',
    'rating.success.description': '評価が送信されました',
    'rating.submitted': '評価済み',
    'review.title': 'レビューを書く',
    'review.rating': '評価',
    'review.comment': 'コメント',
    'review.comment.placeholder': 'ここにコメントを書いてください...',
    'review.submit': 'レビューを送信',
    'review.submit.success': 'レビューを送信しました',
    'review.submit.success.description': 'レビューありがとうございます',
    'review.error.login.required': 'ログインが必要です',
    'review.error.login.required.description': 'レビューを書くにはログインしてください',
    'review.error.rating.required': '評価が必要です',
    'review.error.rating.required.description': '送信する前に評価を選択してください',
    'manager.accounts': 'あなたのアカウント',
    'manager.limit.info': 'さらにLINE OAアカウントを作成できます',
    'manager.limit.reached': 'LINE OAアカウントの制限に達しました',
    
    // Chat translations  
    'chat.title.organizer': '管理者に連絡（マネージャー）',
    'chat.title.general': '管理者に連絡',
    'chat.description.organizer': 'LINE OAアカウント管理について管理者にメッセージを送信',
    'chat.description.general': 'サポートについて管理者にメッセージを送信',
    'chat.placeholder': 'ここにメッセージを入力してください...',
    'chat.send': 'メッセージ送信',
    'chat.empty': 'まだメッセージがありません',
    'chat.response.time': '管理者は24時間以内に返信します',

    // Account edit translations
    'account.edit.title': 'LINE OAアカウント編集',
    'account.edit.button': '編集',
    'account.edit.save': '変更を保存',
    'account.edit.delete': 'アカウント削除',
    'account.edit.success': '保存成功',
    'account.edit.success.description': 'アカウント情報が更新されました',
    'account.edit.error.required': '必須項目を入力してください',
    'account.edit.error.required.description': '名前、説明、LINE IDは必須です',

    // Account form translations
    'account.form.name': 'アカウント名',
    'account.form.name.placeholder': 'LINE OAアカウント名を入力',
    'account.form.description': '説明',
    'account.form.description.placeholder': 'LINE OAアカウントについて説明',
    'account.form.category': 'カテゴリー',
    'account.form.category.placeholder': 'カテゴリーを選択',
    'account.form.lineId': 'LINE ID',
    'account.form.lineId.placeholder': 'LINE IDを入力',
    'account.form.tags': 'タグ',
    'account.form.tags.placeholder': 'タグを入力、例：レストラン、配達',
    'account.form.tags.help': 'タグはカンマで区切ってください',
    'account.form.location': '住所',
    'account.form.location.placeholder': '住所を入力（任意）',

    // Account delete translations
    'account.delete.button': 'アカウント削除',
    'account.delete.success': '削除成功',
    'account.delete.success.description': 'アカウントがシステムから削除されました',
    'account.delete.error.promoted': '削除できません',
    'account.delete.error.promoted.description': 'アカウントを削除する前にプロモーションをキャンセルしてください',
    'account.delete.warning.promoted': 'このアカウントは現在プロモート中です。削除する前にプロモーションをキャンセルしてください。',
    'account.delete.confirm.title': 'アカウント削除の確認',
    'account.delete.confirm.description': 'アカウント"{name}"を削除してもよろしいですか？この操作は元に戻せません。',
    'account.delete.confirm.button': 'アカウント削除',

    // Promotion translations
    'account.promoted': 'プロモート中',
    'promotion.cancel.button': 'プロモートキャンセル',
    'promotion.cancel.success': 'プロモートキャンセル',
    'promotion.cancel.success.description': 'プロモートが正常にキャンセルされました',
    'promotion.cancel.confirm.title': 'プロモートキャンセルの確認',
    'promotion.cancel.confirm.description': '"{name}"のプロモートをキャンセルしてもよろしいですか？',
    'promotion.cancel.confirm.button': 'プロモートキャンセル',
  }
};

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
