import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'th' | 'en' | 'jp';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  th: {
    // Header
    'site.title': 'ค้นหา OA',
    'nav.home': 'หน้าแรก',
    'nav.management': 'หน้าจัดการ',
    'nav.login': 'เข้าสู่ระบบ',
    'nav.logout': 'ออกจากระบบ',
    'nav.profile': 'โปรไฟล์',
    'nav.favorites': 'รายการโปรด',
    
    // Search
    'search.placeholder': 'ค้นหาบัญชี LINE Official...',
    'search.button': 'ค้นหา',
    'search.location.success': 'ได้รับข้อมูลตำแหน่งแล้ว',
    'search.location.searching': 'กำลังค้นหาบัญชี LINE Official ใกล้เคียง...',
    'search.location.error': 'ไม่สามารถหาตำแหน่งได้',
    'search.location.browser.error': 'เบราว์เซอร์ไม่รองรับ',
    
    // Categories
    'category.all': 'ทั้งหมด',
    'category.select': 'เลือกหมวดหมู่',
    'category.expert': 'ผู้เชี่ยวชาญ',
    'category.restaurant': 'ร้านอาหาร',
    'category.transportation': 'การขนส่ง',
    'category.realestate': 'อสังหาริมทรัพย์',
    'category.education': 'การศึกษา',
    'category.travel': 'ท่องเที่ยว',
    'category.entertainment': 'บันเทิง',
    'category.health': 'สุขภาพ',
    'category.beauty': 'ความงาม',
    'category.organization': 'องค์กร/สถาบัน',
    'category.government': 'หน่วยงานรัฐ',
    'category.service': 'ธุรกิจบริการ',
    'category.retail': 'ค้าปลีก/ร้านค้า',
    'category.localbusiness': 'ธุรกิจท้องถิ่นอื่นๆ',
    'category.corporate': 'บริษัท/องค์กรกลุ่ม',
    'category.brand': 'แบรนด์/สินค้า',
    'category.media': 'หนังสือ/นิตยสาร/หนังสือพิมพ์',
    'category.movie': 'ภาพยนตร์',
    'category.music': 'เพลง',
    'category.sports': 'กีฬา',
    'category.tv': 'โทรทัศน์',
    'category.website': 'เว็บไซต์และบล็อก',
    
    // Account Card
    'account.addFriend': 'เพิ่มเพื่อน',
    'account.promotion': 'โปรโมชั่น',
    'account.share': 'แชร์',
    'account.favorites': 'จำนวนที่ถูกเพิ่มในรายการโปรด',
    
    // Home Page
    'home.hero.title': 'เครื่องมือค้นหา',
    'home.hero.subtitle': 'บัญชี LINE Official',
    'home.hero.description': 'ค้นหาบัญชี LINE Official ที่เหมาะสมกับคุณ',
    'home.promoted.title': 'โปรโมชั่น',
    'home.promoted.badge': 'แนะนำ',
    'home.popular.title': 'บัญชียอดนิยม',
    'home.popular.badge': 'ยอดนิยม',
    'home.all.accounts.title': 'บัญชี LINE Official ทั้งหมด',
    'home.all.accounts.badge': 'ทั้งหมด',
    'home.categories.title': 'หมวดหมู่',
    'home.search.results': 'ผลการค้นหา',
    'home.category.results': 'บัญชีในหมวด',
    'home.results.found': 'พบ',
    'home.results.accounts': 'บัญชี',
    'home.no.results.title': 'ไม่พบผลการค้นหา',
    'home.no.results.description': 'ลองค้นหาด้วยคำอื่น',
    
    // Authentication
    'auth.login.title': 'เข้าสู่ระบบ',
    'auth.login.description': 'กรุณาเข้าสู่ระบบบัญชีของคุณ',
    'auth.login.button': 'เข้าสู่ระบบ',
    'auth.login.loading': 'กำลังเข้าสู่ระบบ...',
    'auth.login.success': 'เข้าสู่ระบบสำเร็จ',
    'auth.login.success.description': 'เข้าสู่ระบบเรียบร้อยแล้ว',
    'auth.login.failed': 'เข้าสู่ระบบล้มเหลว',
    'auth.login.failed.description': 'อีเมลหรือรหัสผ่านไม่ถูกต้อง',
    'auth.login.required': 'ต้องเข้าสู่ระบบ',
    'auth.login.required.description': 'กรุณาเข้าสู่ระบบเพื่อใช้งานฟีเจอร์นี้',
    'auth.register.title': 'สมัครสมาชิก',
    'auth.register.button': 'สมัครสมาชิก',
    'auth.register.success': 'สมัครสมาชิกสำเร็จ',
    'auth.register.success.description': 'ยินดีต้อนรับเข้าสู่ระบบ',
    'auth.name': 'ชื่อ',
    'auth.email': 'อีเมล',
    'auth.password': 'รหัสผ่าน',
    'auth.password.placeholder': 'กรอกรหัสผ่าน',
    'auth.phone': 'เบอร์โทรศัพท์',
    'auth.phone.placeholder': 'กรอกเบอร์โทรศัพท์',
    'auth.confirm.password': 'ยืนยันรหัสผ่าน',
    'auth.user.type': 'ประเภทผู้ใช้',
    'auth.user.type.user': 'ผู้ใช้ทั่วไป',
    'auth.user.type.organizer': 'ผู้จัดการ',
    'auth.user.type.admin': 'ผู้ดูแลระบบ',
    'auth.cancel': 'ยกเลิก',
    'auth.error': 'เกิดข้อผิดพลาด',
    'auth.error.description': 'เกิดข้อผิดพลาดในการเข้าสู่ระบบ',
    'auth.error.password.mismatch': 'รหัสผ่านไม่ตรงกัน',
    'auth.error.password.mismatch.description': 'กรุณาตรวจสอบรหัสผ่านให้ตรงกัน',
    'auth.test.accounts': 'บัญชีทดสอบ:',
    'auth.organizer': 'ผู้จัดการ',
    'auth.admin': 'ผู้ดูแลระบบ',
    'auth.general': 'ผู้ใช้ทั่วไป',
    'auth.password.any': 'รหัสผ่าน: อะไรก็ได้',
    
    // Profile
    'profile.title': 'โปรไฟล์ของฉัน',
    'profile.description': 'จัดการข้อมูลส่วนตัวและการตั้งค่า',
    'profile.information': 'ข้อมูลส่วนตัว',
    'profile.security': 'ความปลอดภัย',
    'profile.edit': 'แก้ไขข้อมูล',
    'profile.save': 'บันทึก',
    'profile.update.success': 'อัปเดตโปรไฟล์สำเร็จ',
    'profile.update.success.description': 'ข้อมูลของคุณได้รับการอัปเดตแล้ว',
    'profile.2fa.description': 'การยืนยันตัวตนแบบ 2 ขั้นตอนเปิดใช้งานแล้ว',
    'profile.2fa.enabled': 'เปิดใช้งานแล้ว',
    'profile.change.password': 'เปลี่ยนรหัสผ่าน',
    
    // Favorites
    'favorites.title': 'รายการโปรด',
    'favorites.description': 'บัญชี LINE Official ที่คุณเพิ่มในรายการโปรด',
    'favorites.accounts': 'บัญชี',
    'favorites.empty.title': 'ยังไม่มีรายการโปรด',
    'favorites.empty.description': 'เพิ่มบัญชี LINE Official ที่คุณชื่นชอบเพื่อดูง่ายขึ้น',
    'favorites.browse': 'ค้นหาบัญชี',
    
    // Reviews
    'review.title': 'เขียนรีวิว',
    'review.rating': 'คะแนน',
    'review.comment': 'ความคิดเห็น',
    'review.comment.placeholder': 'แบ่งปันประสบการณ์ของคุณ...',
    'review.submit': 'ส่งรีวิว',
    'review.submit.success': 'ส่งรีวิวสำเร็จ',
    'review.submit.success.description': 'ขอบคุณสำหรับรีวิวของคุณ',
    'review.error.login.required': 'ต้องเข้าสู่ระบบ',
    'review.error.login.required.description': 'กรุณาเข้าสู่ระบบเพื่อเขียนรีวิว',
    'review.error.rating.required': 'ต้องให้คะแนน',
    'review.error.rating.required.description': 'กรุณาให้คะแนนก่อนส่งรีวิว',

    // Share
    'share.title': 'แชร์บัญชี',
    'share.url': 'ลิงก์',
    'share.button': 'แชร์',
    'share.copied.title': 'คัดลอกแล้ว',
    'share.copied.description': 'ลิงก์ถูกคัดลอกไปยังคลิปบอร์ดแล้ว',
    'share.error.title': 'เกิดข้อผิดพลาด',
    'share.error.description': 'ไม่สามารถคัดลอกลิงก์ได้',
    
    // Rating
    'rating.title': 'ให้คะแนน',
    'rating.your.rating': 'คะแนนของคุณ',
    'rating.submitted': 'ส่งคะแนนแล้ว',
    'rating.login.required': 'ต้องเข้าสู่ระบบ',
    'rating.login.required.description': 'กรุณาเข้าสู่ระบบเพื่อให้คะแนน',
    'rating.login.required.message': 'เข้าสู่ระบบเพื่อให้คะแนนบัญชีนี้',
    'rating.success.title': 'ส่งคะแนนสำเร็จ',
    'rating.success.description': 'ขอบคุณสำหรับการให้คะแนน',
    
    // Account Detail
    'account.detail.not.found': 'ไม่พบบัญชี',
    'account.detail.back.home': 'กลับสู่หน้าแรก',
    'account.detail.back': 'กลับ',
    'account.detail.description': 'แนะนำบัญชี',
    'account.detail.tags': 'แท็ก',
    'account.detail.location': 'ที่ตั้ง',
    'account.detail.open.maps': 'เปิดใน Google Maps',
    'account.detail.stats': 'สถิติ',
    'account.detail.views': 'การดู',
    'account.detail.friend.adds': 'เพิ่มเพื่อน',
    'account.detail.favorites': 'รายการโปรด',
    'account.detail.rating': 'คะแนน',
    'account.detail.qr.code': 'QR Code',
    'account.detail.qr.description': 'สแกน QR Code ด้วยแอป LINE เพื่อเพิ่มเพื่อน',
    'account.favorites.count': 'รายการโปรด',
    
    // Manager
    'manager.title': 'แดชบอร์ดผู้จัดการ',
    'manager.description': 'การจัดการบัญชี LINE OA',
    'manager.export.excel': 'ส่งออกข้อมูล Excel',
    'manager.submit.application': 'ส่งใบสมัครลงทะเบียน LINE OA',
    'manager.total.views': 'การดูทั้งหมด',
    'manager.friend.adds': 'การเพิ่มเพื่อน',
    'manager.total.followers': 'ผู้ติดตามทั้งหมด',
    'manager.average.rating': 'คะแนนเฉลี่ย',
    'manager.analytics': 'การวิเคราะห์แนวโน้ม',
    'manager.account.performance': 'ประสิทธิภาพแต่ละบัญชี',
    'manager.my.accounts': 'บัญชีที่จัดการ',
    'manager.promotion.packages': 'แพ็คเกจโปรโมชั่น',
    'manager.transaction.history': 'ประวัติการทำธุรกรรม',
    'manager.views': 'การดู',
    'manager.rating': 'คะแนน',
    'manager.promoting': 'กำลังโปรโมท',
    'manager.purchase': 'ซื้อ',
    'manager.popular': 'ยอดนิยม',
    'manager.completed': 'เสร็จสิ้น',
    'manager.pending': 'รอดำเนินการ',
    'manager.failed': 'ล้มเหลว',
    'manager.export.success': 'ส่งออกข้อมูลสำเร็จ',
    'manager.accounts.limit': 'สามารถสร้างได้สูงสุด 5 บัญชี',
    'manager.limit.reached': 'ถึงขีดจำกัดการสร้างบัญชีแล้ว',
    'manager.limit.info': 'จำนวนบัญชีที่สร้างแล้ว',
    'manager.currency.thb': '฿',
    
    // Admin
    'admin.title': 'แดชบอร์ดผู้ดูแลระบบ',
    'admin.description': 'การจัดการและตรวจสอบระบบ',
    'admin.approved': 'บัญชีที่อนุมัติแล้ว',
    'admin.pending': 'บัญชีรออนุมัติ',
    'admin.revenue': 'รายได้รวม',
    'admin.followers': 'ผู้ติดตามรวม',
    'admin.approve': 'อนุมัติ',
    'admin.reject': 'ปฏิเสธ',
    'admin.approved.message': 'อนุมัติบัญชีแล้ว',
    'admin.rejected.message': 'ปฏิเสธบัญชีแล้ว',
    'admin.review.completed': 'การตรวจสอบบัญชีเสร็จสิ้น',
    'admin.no.pending': 'ไม่มีบัญชีรออนุมัติ',
    'admin.approved.list': 'รายการบัญชีที่อนุมัติ',
    'admin.transaction.list': 'รายการธุรกรรม',
    'admin.pending.accounts': 'บัญชีรออนุมัติ',
    'admin.transaction.id': 'รหัสธุรกรรม',
    'admin.package': 'แพ็คเกจ',
    'admin.organizer.id': 'รหัสผู้จัดการ',
    'admin.date': 'วันที่',
    'admin.submit.application': 'ส่งใบสมัครลงทะเบียน LINE OA',
    'admin.pagination.prev': 'ก่อนหน้า',
    'admin.pagination.next': 'ถัดไป',
    'admin.pagination.page': 'หน้า',
    'admin.pagination.of': 'จาก',
    
    // 404
    '404.title': 'ขออภัย! ไม่พบหน้าที่คุณต้องการ',
    '404.back': 'กลับสู่หน้าแรก'
  },
  en: {
    // Header
    'site.title': 'OA Search',
    'nav.home': 'Home',
    'nav.management': 'Management',
    'nav.login': 'Login',
    'nav.logout': 'Logout',
    'nav.profile': 'Profile',
    'nav.favorites': 'Favorites',
    
    // Search
    'search.placeholder': 'Search LINE Official Accounts...',
    'search.button': 'Search',
    'search.location.success': 'Location obtained',
    'search.location.searching': 'Searching for nearby LINE Official Accounts...',
    'search.location.error': 'Unable to get location',
    'search.location.browser.error': 'Browser not supported',
    
    // Categories
    'category.all': 'All',
    'category.select': 'Select Category',
    'category.expert': 'Expert',
    'category.restaurant': 'Restaurant',
    'category.transportation': 'Transportation',
    'category.realestate': 'Real Estate',
    'category.education': 'Education',
    'category.travel': 'Travel',
    'category.entertainment': 'Entertainment',
    'category.health': 'Health',
    'category.beauty': 'Beauty',
    'category.organization': 'Organization/Institution',
    'category.government': 'Government Agency',
    'category.service': 'Service Business',
    'category.retail': 'Retail/Store',
    'category.localbusiness': 'Other Local Business',
    'category.corporate': 'Corporate/Organization Group',
    'category.brand': 'Brand/Product',
    'category.media': 'Books/Magazines/Newspapers',
    'category.movie': 'Movies',
    'category.music': 'Music',
    'category.sports': 'Sports',
    'category.tv': 'Television',
    'category.website': 'Website & Blog',
    
    // Account Card
    'account.addFriend': 'Add Friend',
    'account.promotion': 'Promotion',
    'account.share': 'Share',
    'account.favorites': 'Favorite Count',
    
    // Home Page
    'home.hero.title': 'Search Tool for',
    'home.hero.subtitle': 'LINE Official Accounts',
    'home.hero.description': 'Find the LINE Official Account that suits you',
    'home.promoted.title': 'Promoted',
    'home.promoted.badge': 'Featured',
    'home.popular.title': 'Popular Accounts',
    'home.popular.badge': 'Popular',
    'home.all.accounts.title': 'All LINE Official Accounts',
    'home.all.accounts.badge': 'All',
    'home.categories.title': 'Categories',
    'home.search.results': 'Search Results',
    'home.category.results': 'Accounts in Category',
    'home.results.found': 'Found',
    'home.results.accounts': 'accounts',
    'home.no.results.title': 'No Results Found',
    'home.no.results.description': 'Try searching with different keywords',
    
    // Authentication
    'auth.login.title': 'Login',
    'auth.login.description': 'Please login to your account',
    'auth.login.button': 'Login',
    'auth.login.loading': 'Logging in...',
    'auth.login.success': 'Login Successful',
    'auth.login.success.description': 'Successfully logged in',
    'auth.login.failed': 'Login Failed',
    'auth.login.failed.description': 'Invalid email or password',
    'auth.login.required': 'Login Required',
    'auth.login.required.description': 'Please login to use this feature',
    'auth.register.title': 'Sign Up',
    'auth.register.button': 'Sign Up',
    'auth.register.success': 'Registration Successful',
    'auth.register.success.description': 'Welcome to the system',
    'auth.name': 'Name',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.password.placeholder': 'Enter password',
    'auth.phone': 'Phone Number',
    'auth.phone.placeholder': 'Enter phone number',
    'auth.confirm.password': 'Confirm Password',
    'auth.user.type': 'User Type',
    'auth.user.type.user': 'General User',
    'auth.user.type.organizer': 'Organizer',
    'auth.user.type.admin': 'System Administrator',
    'auth.cancel': 'Cancel',
    'auth.error': 'Error Occurred',
    'auth.error.description': 'An error occurred during login',
    'auth.error.password.mismatch': 'Passwords do not match',
    'auth.error.password.mismatch.description': 'Please check that passwords match',
    'auth.test.accounts': 'Test Accounts:',
    'auth.organizer': 'Organizer',
    'auth.admin': 'System Admin',
    'auth.general': 'General User',
    'auth.password.any': 'Password: anything',
    
    // Profile
    'profile.title': 'My Profile',
    'profile.description': 'Manage your personal information and settings',
    'profile.information': 'Personal Information',
    'profile.security': 'Security',
    'profile.edit': 'Edit Information',
    'profile.save': 'Save',
    'profile.update.success': 'Profile Updated Successfully',
    'profile.update.success.description': 'Your information has been updated',
    'profile.2fa.description': 'Two-factor authentication is enabled',
    'profile.2fa.enabled': 'Enabled',
    'profile.change.password': 'Change Password',
    
    // Favorites
    'favorites.title': 'Favorites',
    'favorites.description': 'LINE Official Accounts you have favorited',
    'favorites.accounts': 'accounts',
    'favorites.empty.title': 'No Favorites Yet',
    'favorites.empty.description': 'Add LINE Official Accounts you like for easy access',
    'favorites.browse': 'Browse Accounts',
    
    // Reviews
    'review.title': 'Write Review',
    'review.rating': 'Rating',
    'review.comment': 'Comment',
    'review.comment.placeholder': 'Share your experience...',
    'review.submit': 'Submit Review',
    'review.submit.success': 'Review submitted successfully',
    'review.submit.success.description': 'Thank you for your review',
    'review.error.login.required': 'Login required',
    'review.error.login.required.description': 'Please login to write a review',
    'review.error.rating.required': 'Rating required',
    'review.error.rating.required.description': 'Please provide a rating before submitting',

    // Share
    'share.title': 'Share Account',
    'share.url': 'URL',
    'share.button': 'Share',
    'share.copied.title': 'Copied',
    'share.copied.description': 'Link copied to clipboard',
    'share.error.title': 'Error',
    'share.error.description': 'Unable to copy link',
    
    // Rating
    'rating.title': 'Rate Account',
    'rating.your.rating': 'Your Rating',
    'rating.submitted': 'Rating Submitted',
    'rating.login.required': 'Login Required',
    'rating.login.required.description': 'Please login to rate this account',
    'rating.login.required.message': 'Login to rate this account',
    'rating.success.title': 'Rating Submitted',
    'rating.success.description': 'Thank you for your rating',
    
    // Account Detail
    'account.detail.not.found': 'Account Not Found',
    'account.detail.back.home': 'Back to Home',
    'account.detail.back': 'Back',
    'account.detail.description': 'Account Description',
    'account.detail.tags': 'Tags',
    'account.detail.location': 'Location',
    'account.detail.open.maps': 'Open in Google Maps',
    'account.detail.stats': 'Statistics',
    'account.detail.views': 'Views',
    'account.detail.friend.adds': 'Friend Adds',
    'account.detail.favorites': 'Favorites',
    'account.detail.rating': 'Rating',
    'account.detail.qr.code': 'QR Code',
    'account.detail.qr.description': 'Scan QR Code with LINE app to add friend',
    'account.favorites.count': 'favorites',
    
    // Manager
    'manager.title': 'Manager Dashboard',
    'manager.description': 'LINE OA Account Management',
    'manager.export.excel': 'Export Excel Data',
    'manager.submit.application': 'Submit LINE OA Registration',
    'manager.total.views': 'Total Views',
    'manager.friend.adds': 'Friend Adds',
    'manager.total.followers': 'Total Followers',
    'manager.average.rating': 'Average Rating',
    'manager.analytics': 'Analytics Trends',
    'manager.account.performance': 'Account Performance',
    'manager.my.accounts': 'Managed Accounts',
    'manager.promotion.packages': 'Promotion Packages',
    'manager.transaction.history': 'Transaction History',
    'manager.views': 'Views',
    'manager.rating': 'Rating',
    'manager.promoting': 'Promoting',
    'manager.purchase': 'Purchase',
    'manager.popular': 'Popular',
    'manager.completed': 'Completed',
    'manager.pending': 'Pending',
    'manager.failed': 'Failed',
    'manager.export.success': 'Data exported successfully',
    'manager.accounts.limit': 'Maximum 5 accounts allowed',
    'manager.limit.reached': 'Account creation limit reached',
    'manager.limit.info': 'Accounts created',
    'manager.currency.thb': '฿',
    
    // Admin
    'admin.title': 'System Administrator Dashboard',
    'admin.description': 'System management and monitoring',
    'admin.approved': 'Approved Accounts',
    'admin.pending': 'Pending Accounts',
    'admin.revenue': 'Total Revenue',
    'admin.followers': 'Total Followers',
    'admin.approve': 'Approve',
    'admin.reject': 'Reject',
    'admin.approved.message': 'Account approved',
    'admin.rejected.message': 'Account rejected',
    'admin.review.completed': 'Account review completed',
    'admin.no.pending': 'No pending accounts',
    'admin.approved.list': 'Approved Accounts List',
    'admin.transaction.list': 'Transaction History',
    'admin.pending.accounts': 'Pending Accounts',
    'admin.transaction.id': 'Transaction ID',
    'admin.package': 'Package',
    'admin.organizer.id': 'Organizer ID',
    'admin.date': 'Date',
    'admin.submit.application': 'Submit LINE OA Registration',
    'admin.pagination.prev': 'Previous',
    'admin.pagination.next': 'Next',
    'admin.pagination.page': 'Page',
    'admin.pagination.of': 'of',
    
    // 404
    '404.title': 'Sorry! Page not found',
    '404.back': 'Back to Home'
  },
  jp: {
    // Header
    'site.title': 'OA検索',
    'nav.home': 'ホーム',
    'nav.management': '管理',
    'nav.login': 'ログイン',
    'nav.logout': 'ログアウト',
    'nav.profile': 'プロフィール',
    'nav.favorites': 'お気に入り',
    
    // Search
    'search.placeholder': 'LINE公式アカウントを検索...',
    'search.button': '検索',
    'search.location.success': '位置情報を取得しました',
    'search.location.searching': '近くのLINE公式アカウントを検索中...',
    'search.location.error': '位置情報を取得できません',
    'search.location.browser.error': 'ブラウザがサポートされていません',
    
    // Categories
    'category.all': 'すべて',
    'category.select': 'カテゴリを選択',
    'category.expert': '専門家',
    'category.restaurant': '飲食店',
    'category.transportation': '交通',
    'category.realestate': '不動産',
    'category.education': '教育',
    'category.travel': '旅行',
    'category.entertainment': 'エンターテインメント',
    'category.health': '健康',
    'category.beauty': '美容',
    'category.organization': '団体/機関',
    'category.government': '政府機関',
    'category.service': 'サービス業',
    'category.retail': '小売/店舗',
    'category.localbusiness': '地域ビジネスその他',
    'category.corporate': '企業/組織グループ',
    'category.brand': 'ブランド/商品',
    'category.media': '書籍/雑誌/新聞',
    'category.movie': '映画',
    'category.music': '音楽',
    'category.sports': 'スポーツ',
    'category.tv': 'テレビ',
    'category.website': 'ウェブサイト＆ブログ',
    
    // Account Card
    'account.addFriend': '友だち追加',
    'account.promotion': 'プロモーション',
    'account.share': 'シェア',
    'account.favorites': 'お気に入り登録数',
    
    // Home Page
    'home.hero.title': '検索ツール',
    'home.hero.subtitle': 'LINE公式アカウント',
    'home.hero.description': 'あなたに合ったLINE公式アカウントを見つけよう',
    'home.promoted.title': 'プロモーション',
    'home.promoted.badge': 'おすすめ',
    'home.popular.title': '人気アカウント',
    'home.popular.badge': '人気',
    'home.all.accounts.title': 'すべてのLINE公式アカウント',
    'home.all.accounts.badge': 'すべて',
    'home.categories.title': 'カテゴリ',
    'home.search.results': '検索結果',
    'home.category.results': 'カテゴリ内のアカウント',
    'home.results.found': '見つかりました',
    'home.results.accounts': 'アカウント',
    'home.no.results.title': '検索結果が見つかりません',
    'home.no.results.description': '他のキーワードで検索してみてください',
    
    // Authentication
    'auth.login.title': 'ログイン',
    'auth.login.description': 'アカウントにログインしてください',
    'auth.login.button': 'ログイン',
    'auth.login.loading': 'ログイン中...',
    'auth.login.success': 'ログイン成功',
    'auth.login.success.description': 'ログインが完了しました',
    'auth.login.failed': 'ログイン失敗',
    'auth.login.failed.description': 'メールアドレスまたはパスワードが正しくありません',
    'auth.login.required': 'ログインが必要です',
    'auth.login.required.description': 'この機能を使用するにはログインしてください',
    'auth.register.title': 'ユーザー登録',
    'auth.register.button': '登録する',
    'auth.register.success': '登録が完了しました',
    'auth.register.success.description': 'システムへようこそ',
    'auth.name': '名前',
    'auth.email': 'メールアドレス',
    'auth.password': 'パスワード',
    'auth.password.placeholder': 'パスワードを入力',
    'auth.phone': '電話番号',
    'auth.phone.placeholder': '電話番号を入力',
    'auth.confirm.password': 'パスワード確認',
    'auth.user.type': 'ユーザータイプ',
    'auth.user.type.user': '一般ユーザー',
    'auth.user.type.organizer': 'オーガナイザー',
    'auth.user.type.admin': 'システム管理者',
    'auth.cancel': 'キャンセル',
    'auth.error': 'エラーが発生しました',
    'auth.error.description': 'ログイン中にエラーが発生しました',
    'auth.error.password.mismatch': 'パスワードが一致しません',
    'auth.error.password.mismatch.description': 'パスワードが一致していることを確認してください',
    'auth.test.accounts': 'テストアカウント:',
    'auth.organizer': 'オーガナイザー',
    'auth.admin': 'システム管理者',
    'auth.general': '一般ユーザー',
    'auth.password.any': 'パスワード: 何でも',
    
    // Profile
    'profile.title': 'マイプロフィール',
    'profile.description': '個人情報と設定を管理',
    'profile.information': '個人情報',
    'profile.security': 'セキュリティ',
    'profile.edit': '情報を編集',
    'profile.save': '保存',
    'profile.update.success': 'プロフィール更新成功',
    'profile.update.success.description': '情報が更新されました',
    'profile.2fa.description': '2段階認証が有効になっています',
    'profile.2fa.enabled': '有効',
    'profile.change.password': 'パスワード変更',
    
    // Favorites
    'favorites.title': 'お気に入り',
    'favorites.description': 'お気に入りに登録したLINE公式アカウント',
    'favorites.accounts': 'アカウント',
    'favorites.empty.title': 'お気に入りがありません',
    'favorites.empty.description': 'お気に入りのLINE公式アカウントを追加して簡単にアクセス',
    'favorites.browse': 'アカウントを探す',
    
    // Reviews
    'review.title': 'レビューを書く',
    'review.rating': '評価',
    'review.comment': 'コメント',
    'review.comment.placeholder': 'あなたの体験をシェアしてください...',
    'review.submit': 'レビューを送信',
    'review.submit.success': 'レビューを送信しました',
    'review.submit.success.description': 'レビューありがとうございます',
    'review.error.login.required': 'ログインが必要です',
    'review.error.login.required.description': 'レビューを書くにはログインしてください',
    'review.error.rating.required': '評価が必要です',
    'review.error.rating.required.description': '送信前に評価を入力してください',

    // Share
    'share.title': 'アカウントをシェア',
    'share.url': 'URL',
    'share.button': 'シェア',
    'share.copied.title': 'コピーしました',
    'share.copied.description': 'リンクをクリップボードにコピーしました',
    'share.error.title': 'エラー',
    'share.error.description': 'リンクをコピーできませんでした',
    
    // Rating
    'rating.title': 'アカウントを評価',
    'rating.your.rating': 'あなたの評価',
    'rating.submitted': '評価を送信しました',
    'rating.login.required': 'ログインが必要',
    'rating.login.required.description': 'このアカウントを評価するにはログインしてください',
    'rating.login.required.message': 'このアカウントを評価するにはログインしてください',
    'rating.success.title': '評価を送信しました',
    'rating.success.description': '評価ありがとうございます',
    
    // Account Detail
    'account.detail.not.found': 'アカウントが見つかりません',
    'account.detail.back.home': 'ホームに戻る',
    'account.detail.back': '戻る',
    'account.detail.description': 'アカウント紹介',
    'account.detail.tags': 'タグ',
    'account.detail.location': '場所',
    'account.detail.open.maps': 'Google Mapsで開く',
    'account.detail.stats': '統計',
    'account.detail.views': '閲覧数',
    'account.detail.friend.adds': '友だち追加',
    'account.detail.favorites': 'お気に入り',
    'account.detail.rating': '評価',
    'account.detail.qr.code': 'QRコード',
    'account.detail.qr.description': 'LINEアプリでQRコードをスキャンして友だち追加',
    'account.favorites.count': 'お気に入り',
    
    // Manager
    'manager.title': 'オーガナイザーダッシュボード',
    'manager.description': 'LINE OAアカウント管理',
    'manager.export.excel': 'Excelデータエクスポート',
    'manager.submit.application': 'LINE OA登録申請を提出',
    'manager.total.views': '総閲覧数',
    'manager.friend.adds': '友だち追加数',
    'manager.total.followers': '総フォロワー数',
    'manager.average.rating': '平均評価',
    'manager.analytics': 'アクセス推移',
    'manager.account.performance': 'アカウント別パフォーマンス',
    'manager.my.accounts': '管理中のアカウント',
    'manager.promotion.packages': 'プロモーションパッケージ',
    'manager.transaction.history': '取引履歴',
    'manager.views': '閲覧数',
    'manager.rating': '評価',
    'manager.promoting': 'プロモーション中',
    'manager.purchase': '購入する',
    'manager.popular': '人気',
    'manager.completed': '完了',
    'manager.pending': '処理中',
    'manager.failed': '失敗',
    'manager.export.success': 'データのエクスポートが完了しました',
    'manager.accounts.limit': '最大5アカウントまで作成可能',
    'manager.limit.reached': 'アカウント作成の上限に達しました',
    'manager.limit.info': '作成済みアカウント数',
    'manager.currency.thb': '฿',
    
    // Admin
    'admin.title': 'グローバル管理者ダッシュボード',
    'admin.description': 'システム全体の管理と監視',
    'admin.approved': '承認済みアカウント',
    'admin.pending': '保留中アカウント',
    'admin.revenue': '総売上',
    'admin.followers': '総フォロワー数',
    'admin.approve': '承認',
    'admin.reject': '却下',
    'admin.approved.message': 'アカウントを承認しました',
    'admin.rejected.message': 'アカウントを却下しました',
    'admin.review.completed': 'アカウントの審査が完了しました',
    'admin.no.pending': '承認待ちのアカウントはありません',
    'admin.approved.list': '承認済みアカウント一覧',
    'admin.transaction.list': '取引履歴・支払い確認',
    'admin.pending.accounts': '承認待ちアカウント',
    'admin.transaction.id': '取引ID',
    'admin.package': 'パッケージ',
    'admin.organizer.id': 'オーガナイザーID',
    'admin.date': '日付',
    'admin.submit.application': 'LINE OA登録申請を提出',
    'admin.pagination.prev': '前へ',
    'admin.pagination.next': '次へ',
    'admin.pagination.page': 'ページ',
    'admin.pagination.of': '/',
    
    // 404
    '404.title': '申し訳ございません！ページが見つかりません',
    '404.back': 'ホームに戻る'
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

interface LanguageProviderProps {
  children: ReactNode;
}

export function LanguageProvider({ children }: LanguageProviderProps) {
  const [language, setLanguage] = useState<Language>('th');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
